import ProjectDescription

let workspace = Workspace(
  name: "BobPT",
  projects: [
    "Projects/App/BobPT",
    "Projects/Feature/BobPTFeature",
    "Projects/Core/BobPTCore",
    "Projects/Domain/BobPTDomain",
    "Projects/Share/BobPTShare"
  ],
  additionalFiles: [
    "Xcconfig/**"
  ],
  generationOptions: .options(
    enableAutomaticXcodeSchemes: false,
    autogeneratedWorkspaceSchemes: .enabled(codeCoverageMode: .all),
    renderMarkdownReadme: true
  )
)
